# Disable RGBLED_WIDGET to avoid conflict with studio-rpc-usb-uart snippet
CONFIG_RGBLED_WIDGET=n

# Uncomment these two lines to add support for left encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
